version: '2'
services:
  wordpress:
    build: ./container/wp
    container_name: project_wp
    restart: 'always'
    volumes:
      - ./container/wp/html/assets:/var/www/html/assets
    ports:
      - 80:80
    links:
      - mysql
    environment:
      DOMAIN: project.test
      APACHE_DOCROOT: /var/www/html
      APACHE_LOG_DIR: /var/log/apache2
      PROJECT_NAME: project
      WP_DB_HOST: mysql:3306
      WP_DB_NAME: project
      WP_DB_USER: uuki
      WP_DB_PASSWORD: example
  mysql:
    image: mysql:5.7.16
    container_name: project_mysql
    restart: 'always'
    ports:
      - 3306:3306
    working_dir: /sql
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: project
      MYSQL_USER: uuki
      MYSQL_PASSWORD: example
volumes:
  db-data:
    driver: local